# Generated by Django 4.0.2 on 2022-05-11 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='first_name',
            field=models.TextField(max_length=230, verbose_name='first_name'),
        ),
        migrations.AlterField(
            model_name='client',
            name='gender',
            field=models.CharField(blank=True, choices=[('F', 'Женщина'), ('M', 'Мужчина'), ('U', 'Не указан')], default='U', max_length=1),
        ),
        migrations.AlterField(
            model_name='client',
            name='last_name',
            field=models.TextField(max_length=250, verbose_name='last_name'),
        ),
        migrations.AlterField(
            model_name='client',
            name='password',
            field=models.CharField(max_length=250, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='client',
            name='username',
            field=models.CharField(max_length=250, unique=True, verbose_name='client_name'),
        ),
    ]
