from .base import *
from .email import *

# SECRET_KEY must be generated by the command before the deploy:
# $./generate_secret_key.sh
with open(ROOT_DIR.path('secretkey.txt')) as f:
    SECRET_KEY = f.read().strip()

DEBUG = False

ROOT_URLCONF = 'config.urls'

ALLOWED_HOSTS = [
    env('SERVER_HOST'),
]

DATABASES = {
    'default': {
        'ENGINE': env.db('DB_ENGINE'),
        'NAME': env('DB_NAME'),
        'USER': env('DB_USER'),
        'PASSWORD': env('DB_PASSWORD'),
        'HOST': env('DB_HOST'),
        'PORT': env('DB_PORT'),
    }
}
